"use client";

import { useState } from 'react';
import { motion } from 'framer-motion';
import { FilePdf, Download, SpinnerGap, Check, FileText, Stamp, CalendarBlank } from '@phosphor-icons/react';
import { cn } from '@/lib/utils';
import type { Contract } from '@/lib/types';

interface PdfExportProps {
  contract: Contract;
}

export default function PdfExport({ contract }: PdfExportProps) {
  const [generating, setGenerating] = useState(false);
  const [generated, setGenerated] = useState(false);
  const [format, setFormat] = useState<'standard' | 'legal' | 'compact'>('standard');

  const handleGenerate = async () => {
    setGenerating(true);
    // Simulate PDF generation
    await new Promise(r => setTimeout(r, 2500));
    setGenerating(false);
    setGenerated(true);
  };

  const handleDownload = () => {
    // Create a simple text-based document for download
    const content = `
AGREEMENT: ${contract.title}
Category: ${contract.category}
Status: ${contract.status}
Date: ${new Date(contract.createdAt).toLocaleDateString()}
Jurisdiction: ${contract.jurisdiction}

PARTIES:
${contract.parties.map(p => `- ${p.name} (${p.email}) — ${p.role}${p.signedAt ? ` [Signed: ${new Date(p.signedAt).toLocaleDateString()}]` : ' [Pending]'}`).join('\n')}

CLAUSES:
${contract.clauses.map((c, i) => `${i + 1}. ${c.title}\n   ${c.content}`).join('\n\n')}

${contract.totalAmount ? `TOTAL VALUE: ${contract.currency} ${contract.totalAmount.toLocaleString()}` : ''}

PAYMENT SCHEDULE:
${contract.paymentSchedule.length > 0 ? contract.paymentSchedule.map(p => `- ${contract.currency} ${p.amount} — Due: ${new Date(p.dueDate).toLocaleDateString()} — Status: ${p.status}`).join('\n') : 'No payments scheduled.'}

---
Generated by AgreeMint • ${new Date().toLocaleString()}
This document is for reference purposes. Consult a legal professional for binding agreements.
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${contract.title.replace(/\s+/g, '_')}_Agreement.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Format Selection */}
      <div className="space-y-3">
        <p className="text-[10px] font-black text-text-3 uppercase tracking-[0.3em]">Document Style</p>
        <div className="grid grid-cols-3 gap-3">
          {[
            { id: 'standard', label: 'Standard', desc: 'Clean & simple' },
            { id: 'legal', label: 'Legal', desc: 'Formal layout' },
            { id: 'compact', label: 'Compact', desc: 'One page' },
          ].map(f => (
            <button
              key={f.id}
              onClick={() => setFormat(f.id as any)}
              className={cn(
                "p-4 rounded-xl border text-center transition-all",
                format === f.id ? "bg-emerald/10 border-emerald/30 text-emerald" : "bg-white/[0.03] border-white/10 text-text-3"
              )}
            >
              <p className="text-[10px] font-black uppercase tracking-widest">{f.label}</p>
              <p className="text-[8px] opacity-50 mt-1 uppercase tracking-wider">{f.desc}</p>
            </button>
          ))}
        </div>
      </div>

      {/* Preview */}
      <div className="p-8 rounded-2xl bg-white/[0.03] border border-white/10 space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <FileText size={20} className="text-emerald" weight="bold" />
            <p className="text-sm font-black text-white">{contract.title}</p>
          </div>
          <span className="text-[9px] font-black text-text-3 uppercase tracking-widest">{format}</span>
        </div>

        <div className="space-y-2 text-[10px] text-text-3 uppercase tracking-widest">
          <div className="flex items-center gap-2">
            <Stamp size={14} weight="bold" /> <span>{contract.jurisdiction || 'General'}</span>
          </div>
          <div className="flex items-center gap-2">
            <CalendarBlank size={14} weight="bold" /> <span>{new Date(contract.createdAt).toLocaleDateString()}</span>
          </div>
          <div className="flex items-center gap-2">
            <FilePdf size={14} weight="bold" /> <span>{contract.clauses.length} Clauses • {contract.parties.length} Parties</span>
          </div>
        </div>
      </div>

      {/* Actions */}
      {!generated ? (
        <button
          onClick={handleGenerate}
          disabled={generating}
          className="w-full py-5 rounded-2xl bg-emerald text-[#010101] text-[11px] font-black uppercase tracking-widest flex items-center justify-center gap-3 disabled:opacity-50 shadow-[0_0_30px_rgba(0,255,209,0.2)] hover:shadow-[0_0_40px_rgba(0,255,209,0.4)] transition-all"
        >
          {generating ? (
            <><SpinnerGap size={20} className="animate-spin" weight="bold" /> Generating PDF...</>
          ) : (
            <><FilePdf size={20} weight="bold" /> Generate PDF</>
          )}
        </button>
      ) : (
        <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-3">
          <div className="p-4 rounded-xl bg-emerald/10 border border-emerald/20 flex items-center gap-3">
            <Check size={18} className="text-emerald" weight="bold" />
            <p className="text-[10px] font-black text-emerald uppercase tracking-widest">Document ready!</p>
          </div>
          <button
            onClick={handleDownload}
            className="w-full py-5 rounded-2xl bg-emerald text-[#010101] text-[11px] font-black uppercase tracking-widest flex items-center justify-center gap-3 shadow-[0_0_30px_rgba(0,255,209,0.2)]"
          >
            <Download size={20} weight="bold" /> Download
          </button>
        </motion.div>
      )}
    </div>
  );
}
